{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtone.android",
    "module": "AndroidAutoScreenShot",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.1.aar",
          "url": "AndroidAutoScreenShot-0.0.1.aar",
          "size": 153672,
          "sha512": "2f4b40974d954200dc389cee987829aa3ca42e6a82831772207c63a23a87f4e31ecc40ea7a50689120aa68b6e1bc2bd334be0ec29228af882b9f4bfc8cba7653",
          "sha256": "3a7ec93b2188c599833cdd1a4de36414c446783d40231f79dbe098a6267123e7",
          "sha1": "3c32b6531e265c188820b5329129e5ded60fc90e",
          "md5": "d182fe374dbf2a19dc4ebe7f93682916"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.1.aar",
          "url": "AndroidAutoScreenShot-0.0.1.aar",
          "size": 153672,
          "sha512": "2f4b40974d954200dc389cee987829aa3ca42e6a82831772207c63a23a87f4e31ecc40ea7a50689120aa68b6e1bc2bd334be0ec29228af882b9f4bfc8cba7653",
          "sha256": "3a7ec93b2188c599833cdd1a4de36414c446783d40231f79dbe098a6267123e7",
          "sha1": "3c32b6531e265c188820b5329129e5ded60fc90e",
          "md5": "d182fe374dbf2a19dc4ebe7f93682916"
        }
      ]
    }
  ]
}
