{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtone.android",
    "module": "AndroidAutoScreenShot",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.2.aar",
          "url": "AndroidAutoScreenShot-0.0.2.aar",
          "size": 156303,
          "sha512": "c63904b0f4178906f68da825e29e36d93c6e9ad9b8b136b212b8c625a99b103e7fe43eadd82888bf4cc0a7569f2d86a715bc4b9999fff29eb45155578abdc27d",
          "sha256": "d9beef6b10947c229c04ba118a9f341cdcc3c00b434a7b3148884ce39e20e5e1",
          "sha1": "2e8128b3cd309d8dbf1248894bc78bcc4bb43d19",
          "md5": "efd6f66bd45cfb38cc4f14ff92eab5ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.2.aar",
          "url": "AndroidAutoScreenShot-0.0.2.aar",
          "size": 156303,
          "sha512": "c63904b0f4178906f68da825e29e36d93c6e9ad9b8b136b212b8c625a99b103e7fe43eadd82888bf4cc0a7569f2d86a715bc4b9999fff29eb45155578abdc27d",
          "sha256": "d9beef6b10947c229c04ba118a9f341cdcc3c00b434a7b3148884ce39e20e5e1",
          "sha1": "2e8128b3cd309d8dbf1248894bc78bcc4bb43d19",
          "md5": "efd6f66bd45cfb38cc4f14ff92eab5ea"
        }
      ]
    }
  ]
}
