{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtone.android",
    "module": "AndroidAutoScreenShot",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.2.0.aar",
          "url": "AndroidAutoScreenShot-0.2.0.aar",
          "size": 199697,
          "sha512": "de69c6fa2da41f33f1e892e7246dd91d68d2679b669687513ae227a55cdd127c06b4088d71d9acaba02f3ff43faaa619b7d39d5494d0a8c6770eab962a013605",
          "sha256": "ddabadc8125a70df9d7fcb0dc3607a80623fe51df4ea3465c23da8e4f4f83a8c",
          "sha1": "646cc2ef999f161a6087c54f5b4f1be1cd70bcfc",
          "md5": "dad45d8894fa16c83034ccbb929aa7f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.2.0.aar",
          "url": "AndroidAutoScreenShot-0.2.0.aar",
          "size": 199697,
          "sha512": "de69c6fa2da41f33f1e892e7246dd91d68d2679b669687513ae227a55cdd127c06b4088d71d9acaba02f3ff43faaa619b7d39d5494d0a8c6770eab962a013605",
          "sha256": "ddabadc8125a70df9d7fcb0dc3607a80623fe51df4ea3465c23da8e4f4f83a8c",
          "sha1": "646cc2ef999f161a6087c54f5b4f1be1cd70bcfc",
          "md5": "dad45d8894fa16c83034ccbb929aa7f5"
        }
      ]
    }
  ]
}
