{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtone.android",
    "module": "AndroidAutoScreenShot",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.5.aar",
          "url": "AndroidAutoScreenShot-0.0.5.aar",
          "size": 136414,
          "sha512": "987d7bf72bf9d974d48de242a8ec3ceb3303ed46dba10858def3a229d3bf13489eb7ed3dac0ac76f6fe6dc9e644739dcfb44aaa2d7afbb5de25e447130babb75",
          "sha256": "e72b038476aacd297731c51325dc71c01d2e2cfbca8a87bdf7493bb5df6a5d16",
          "sha1": "726085e26c710435f5dce1bf090317505643a2c1",
          "md5": "bfb152c2b8c45bc934de5a7e6b3b3033"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.5.aar",
          "url": "AndroidAutoScreenShot-0.0.5.aar",
          "size": 136414,
          "sha512": "987d7bf72bf9d974d48de242a8ec3ceb3303ed46dba10858def3a229d3bf13489eb7ed3dac0ac76f6fe6dc9e644739dcfb44aaa2d7afbb5de25e447130babb75",
          "sha256": "e72b038476aacd297731c51325dc71c01d2e2cfbca8a87bdf7493bb5df6a5d16",
          "sha1": "726085e26c710435f5dce1bf090317505643a2c1",
          "md5": "bfb152c2b8c45bc934de5a7e6b3b3033"
        }
      ]
    }
  ]
}
