{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.xtone.android",
    "module": "ui-scan-android-sdk",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-scan-android-sdk-0.3.0.aar",
          "url": "ui-scan-android-sdk-0.3.0.aar",
          "size": 194499,
          "sha512": "dd5abd057e478fb1737888150f009b17ec684be0cc1b248f28a4680af2d96397a2307fd1f6027a9283b19d260fe5dd821943ea01d7f5e8f70e2f357e26a0e4af",
          "sha256": "4d8eeca61e2e1f67d332e4aa3caf567b46527b63475b67459c7eccbc3f57ce22",
          "sha1": "6d2f48c1479285d2b766a7946cd8599cf0d17b7d",
          "md5": "7bc047288df94a47ff7a9bdf5ad74a5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-scan-android-sdk-0.3.0.aar",
          "url": "ui-scan-android-sdk-0.3.0.aar",
          "size": 194499,
          "sha512": "dd5abd057e478fb1737888150f009b17ec684be0cc1b248f28a4680af2d96397a2307fd1f6027a9283b19d260fe5dd821943ea01d7f5e8f70e2f357e26a0e4af",
          "sha256": "4d8eeca61e2e1f67d332e4aa3caf567b46527b63475b67459c7eccbc3f57ce22",
          "sha1": "6d2f48c1479285d2b766a7946cd8599cf0d17b7d",
          "md5": "7bc047288df94a47ff7a9bdf5ad74a5b"
        }
      ]
    }
  ]
}
