{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xtone.android",
    "module": "AndroidAutoScreenShot",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.6.aar",
          "url": "AndroidAutoScreenShot-0.0.6.aar",
          "size": 137043,
          "sha512": "c537f35655c3695c654b0a9ee0328b10f228cd29a8c4c1ee0ffe51c226cb390a252d4ac34216ae412fbc3915f168ea8d8404fbb374db2f5c0dfb6d66257f01cf",
          "sha256": "3e730a34017d0b457f549576ea50d86bbd4bdbe4815b97a27528aa4786aa948f",
          "sha1": "6775304b966a64d99464489f2630b682f0f7c713",
          "md5": "16cdbdd1cf4dacef752448576d0b524a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.0.6.aar",
          "url": "AndroidAutoScreenShot-0.0.6.aar",
          "size": 137043,
          "sha512": "c537f35655c3695c654b0a9ee0328b10f228cd29a8c4c1ee0ffe51c226cb390a252d4ac34216ae412fbc3915f168ea8d8404fbb374db2f5c0dfb6d66257f01cf",
          "sha256": "3e730a34017d0b457f549576ea50d86bbd4bdbe4815b97a27528aa4786aa948f",
          "sha1": "6775304b966a64d99464489f2630b682f0f7c713",
          "md5": "16cdbdd1cf4dacef752448576d0b524a"
        }
      ]
    }
  ]
}
