{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.xtone.android",
    "module": "AndroidAutoScreenShot",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.3.0.aar",
          "url": "AndroidAutoScreenShot-0.3.0.aar",
          "size": 194497,
          "sha512": "6f404cb6516c4cc7f2359e6e49e43825eec59f58c2ba5e0060ef48542f43aeecebd6007148ee687adadcd43cc781d00d6fe80aad86be2fdfb7dfae23b753539a",
          "sha256": "784fea6a8332dc9e4dceb18741f2cbe31570750b661122f664233c66000abe0f",
          "sha1": "8e9afb8bf0b919c67d7d30fde5d837f97eacb1f1",
          "md5": "d99705fa0448e5c389106050fb261f08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.slack.eithernet",
          "module": "eithernet",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidAutoScreenShot-0.3.0.aar",
          "url": "AndroidAutoScreenShot-0.3.0.aar",
          "size": 194497,
          "sha512": "6f404cb6516c4cc7f2359e6e49e43825eec59f58c2ba5e0060ef48542f43aeecebd6007148ee687adadcd43cc781d00d6fe80aad86be2fdfb7dfae23b753539a",
          "sha256": "784fea6a8332dc9e4dceb18741f2cbe31570750b661122f664233c66000abe0f",
          "sha1": "8e9afb8bf0b919c67d7d30fde5d837f97eacb1f1",
          "md5": "d99705fa0448e5c389106050fb261f08"
        }
      ]
    }
  ]
}
